apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-grpc-ping
spec:
  secretName: {{ .Values.secretName | default ( printf "%s-grpc-ping-tls" .Release.Name ) }}
  commonName: {{ .Release.Name }}
  dnsNames:
  - {{ .Values.hostname }}
  issuerRef:
    name:  {{ .Values.issuer }}
    kind: ClusterIssuer
    group: cert-manager.io