apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
  name: {{ .Release.Name }}-grpc-ping
spec:
  parentRefs:
  - name: {{ .Values.parent }}
  hostnames:
  - {{ .Values.hostname }}
  rules:
  - backendRefs:
    - name: {{ .Release.Name }}-grpc-ping
      port: grpc