apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-grpc-ping
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-grpc-ping
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}-grpc-ping
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-grpc-ping
    spec:
      containers:
      - name: grpc-ping
        image: {{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag | default .Release.AppVersion }}
        ports:
          - containerPort: 8080
            name: grpc
        command: ["/grpc-ping"]
        args:
        - "serve"
{{- if .Values.tls.secretName }}
        - "--tls-key"
        - "/var/run/grpc-ping/tls.key"
        - "--tls-cert"
        - "/var/run/grpc-ping/tls.crt"
        volumeMounts:
          - name: tls
            mountPath: /var/run/grpc-ping
      volumes:
      - name: tls
        secret:
          secretName: {{ .Values.tls.secretName }}
{{- end }}
