apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-grpc-ping
spec:
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}-grpc-ping
  type: ClusterIP
  ports:
  - name: grpc
    protocol: TCP
    port: 50051
    targetPort: grpc
